name: build
on:
  push:
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
      - run: nix build
      - run: nix build .#container
      - run: docker load < result
      - name: authenticate docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        run: |
          tag=$(git rev-parse --short HEAD)
          docker tag openedge:$tag ghcr.io/cmoog/openedge:$tag
          docker push ghcr.io/cmoog/openedge:$tag
      - name: tag latest
        if: github.ref == 'refs/heads/master'
        run: | 
          tag=$(git rev-parse --short HEAD)
          docker tag openedge:$tag ghcr.io/cmoog/openedge:latest
          docker push ghcr.io/cmoog/openedge:latest
